/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatAssistant: typeof import('./src/components/ChatAssistant.vue')['default']
    DocumentList: typeof import('./src/components/DocumentList.vue')['default']
    DocumentOutline: typeof import('./src/components/DocumentOutline.vue')['default']
    EditableTable: typeof import('./src/components/EditableTable.vue')['default']
    EmptyChapter: typeof import('./src/components/EmptyChapter.vue')['default']
    HeaderLogo: typeof import('./src/components/HeaderLogo.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RecognizeResultDrawer: typeof import('./src/components/RecognizeResultDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
